Django_app/Django_Web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

Django_app/api/urls.py
from django.urls import path

from api.views import (
            # CreateListAPIViewFunctionBased, 
            # RetrieveUpdateAPIViewFunctionBased,
            # DeleteAPIViewFunctionBased,
            EvrythingAPIViewClassBased,

        )

urlpatterns = [
    # function based
    # path('', CreateListAPIViewFunctionBased, name='apiview'),
    # path('<int:pk>/', RetrieveUpdateAPIViewFunctionBased, name='idapiview'),
    # path('<int:pk>/delete', DeleteAPIViewFunctionBased, name='deleteapiview'),


    # class based
    path('', EvrythingAPIViewClassBased.as_view()),
    path('<int:pk>/', EvrythingAPIViewClassBased.as_view()),  
]

Django_app/main/urls.py
from django.urls import path

from main.views import (
            Login, Signup, 
            logout, homepage,
            SearchView,
        )

app_name = "main"

urlpatterns = [
    path('', homepage, name='homepage'),
    path('login', Login.as_view(), name='login'),
    path('signup', Signup.as_view(), name='signup'),
    path('logout', logout, name='logout'),
    path("search/", SearchView.as_view(), name="search"),
]

Django_app/main/models.py
from django.db import models


class PatientProfile(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField()
    description = models.TextField()
    email = models.EmailField()


class Doctor(models.Model):
    patient = models.ManyToManyField(PatientProfile)
    doctor = models.CharField(max_length=100)
    password = models.CharField(max_length=100, default=1234)
    field_doctor = models.CharField(max_length=255)

    @staticmethod
    def get_customers_by_name(doctor):
        try:
            return Doctor.objects.get(doctor=doctor)
        except:
            return False

Django_app/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import check_password
from django.contrib.auth.hashers import make_password 
from django.views.generic import ListView
from django.db.models import Q
from django.http import HttpResponse
from django.views import View 
from django.contrib import messages 

from rest_framework import generics
from api.serializers import SerializetionPatient 

from main.models import Doctor, PatientProfile


def validateCustomer(customer):
    error_message = None
    if (not customer.name):
        error_message = "Please Enter your First Name !!"
    elif len(customer.name) < 3:
        error_message = 'First Name must be 3 char long or more'
    elif not customer.last_name:
        error_message = 'Please Enter your Last Name'
    elif len(customer.last_name) < 3:
        error_message = 'Last Name must be 3 char long or more'
    elif len(customer.email) < 5:
        error_message = 'Email must be 5 char long'

    return error_message


class Login(View):

    return_url = None
    def get(self, request):
        Login.return_url = request.GET.get("return_url")
        return render(request=request, template_name='main/login.html')

    def post(self, request):
        name = request.POST.get("doctor")
        password = request.POST.get("password")
        doctor = Doctor.get_customers_by_name(name)
        print(doctor)
        error_message = None
        if doctor:
            if doctor.doctor==name and doctor.password==password:
                request.session['doctor'] = doctor.id
                return_url = None
                return redirect("main:homepage")
            else:
                error_message = 'Invalid !!'

        else:
            error_message = 'Invalid !!'

        print(name, password)
        return render(request=request, 
                      template_name="main/login.html", 
                      context={"error":error_message})


class Signup(View):

    def get(self, request):
        return render(request=request, 
                      template_name="main/signup.html")

    def post(self, request):
        postData = request.POST 
        first_name = postData.get('firstname')
        last_name = postData.get('lastname')
        phone = postData.get('phone')
        email = postData.get('email')
        password = postData.get('password')
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }

        error_message = None
        customer = Doctor(firstname=first_name,
                             lastname=last_name,
                             phone=phone,
                             email=email,
                             password=password)

        error_message = validateCustomer(customer)
        print(error_message)
        if not error_message:
            print(first_name, last_name, phone, email, password)
            customer.password = make_password(customer.password)
            customer.save()
            return redirect('main:homepage')
        else:
            data = {
                'error': error_message,
                'values': value
            }
            return render(request=request, 
                          template_name='main/signup.html', 
                          context={"data":data})


class SearchView(ListView):
    model = PatientProfile
    template_name = "main/search_result.html"

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = PatientProfile.objects.filter(
            Q(name__icontains=query),
            Q(last_name__icontains=query),
            Q(age__icontains=query),
            Q(email__icontains=query),
        )
        if object_list.exists():
            return object_list
        else:
            return messages.info(self.request, "Your data is't available...")


def logout(request):
    request.session.clear()
    return redirect('main:homepage')


def homepage(request):
    # this is a good thinking about it and great work...
    id_session = request.session.get('doctor')
    if id_session is not None:
        postdata = request.POST 
        name = postdata.get('name')
        lastname = postdata.get('lastname')
        age = postdata.get('age')
        description = postdata.get('description')
        email = postdata.get('email')

        values = {
            'name': name, 
            'last_name': lastname,
            'age': age,
            'description': description,
            'email': email
        }

        error_message = None
        patient_values = PatientProfile(name=name,
                                last_name=lastname,
                                age=age,
                                description=description,
                                email=email)
        error_message = validateCustomer(patient_values)
        print(error_message)

        doctor_profile_data = Doctor.objects.get(id=request.session['doctor'])
        if not error_message:
            print(values)
            patient_values.save()
            doctor_profile_data.patient.add(patient_values)
            return redirect('main:homepage')
            
            
        return render(request, 
                    template_name='main/home.html',
                    context={'data':doctor_profile_data})

    return render(request, 
                  template_name='main/home.html') 

Django_app/main/templates/main/base.html
<!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


<ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>

    <div class="nav-wrapper">
      {% if request.session.doctor %}


      <a href="#!" class="brand-logo">{{data.doctor}}</a>
      <ul class="right hide-on-med-and-down">

      {% else %}
        <a href="#!" class="brand-logo">Doctors Profiles</a>
        <ul class="right hide-on-med-and-down">
    
      {% endif %}

        {% if request.session.doctor %}

          <ul>
            <li><a  href="/logout">Logout Doctors</a></li>
          </ul>
        {% else %}
       
        <ul>
          
          <li><a href="/login">Login Doctors</a></li>
          <li><a href="/signup">Sign up</a></li>

        </ul>

        {% endif %}
   
        
        </ul>
    </div>
  </nav>
  
  <nav>
    <div class="nav-wrapper">

        <div class="search-box">
          
          <form action="{% url 'main:search' %}" method="get">  
          <input name="q" type="text" placeholder="Search patiants">


          <button class="btn waves-effect waves-light">Search

          </button>
        
          <!-- <label class="label-icon" for="search"><i class="material-icons">search</i></label> -->
          <!-- <i class="material-icons">close</i> -->
        </form>
      </div>
        </div>

  </nav>

  <body>
  {% block content %}{% endblock %}

</body>

Django_app/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}


<div class="container">
    <div class="p-3 m-3">
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">
            
            </div>
            <h3 class="alert alert-light rounded-pill" style="text-align:center" >Patient Profile</h3>
            <form method="POST">
                
                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}

                {% if request.session.doctor %}
                <div class="form-group">
                    <label for="">name</label>
                    <input type="text" 
                    name="name" 
                    id=""
                     class="form-control form-control-sm" >
                </div>

                <div class="form-group">
                    <label for="">last name</label>
                    <input type="text" 
                    name="lastname" 
                    id=""
                     class="form-control form-control-sm" >
                </div>


                <div class="form-group">
                    <label for="">age</label>
                    <input type="text" 
                    name="age" 
                    id=""
                     class="form-control form-control-sm" >
                </div>

                <div class="form-group">
                    <label for="">description</label>
                    <input type="text" 
                    name="description" 
                    id=""
                     class="form-control form-control-sm" >
                </div>


                <!-- email -->
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id=""
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>

                <button type="submit" class="btn btn-sm btn-success col-lg-12">Save Data</button>
                
                {% endif %}

            </form>
        </div>
    </div>
</div>


{% endblock %}

Django_app/main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Login</title>
</head>
{% block content %}

<div class="container">
    <div class="p-3 m-3">
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">
            
            </div>
            <h3 class="alert alert-light rounded-pill" style="text-align:center" >Login Doctors</h3>
            <form action="/login" method="POST">
                
                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}

                <!-- email -->
                <div class="form-group">
                    <label for="">Doctor</label>
                    <input required type="text" name="doctor" id=""
                    class="form-control form-control-sm" >
                </div>


                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id=""
                     class="form-control form-control-sm" >
                </div>


                <!--Checkme button-->
            <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>

                <button type="submit" class="btn btn-sm btn-success col-lg-12">Login</button>


                
            </form>
        </div>
    </div>
</div>

{% endblock %}

Django_app/main/templates/main/search_result.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #070000;
  text-align: left;
  padding: 8px;
}

tr:nth-child(n) {
  background-color: #ffffff;
}
</style>
</head>
<body>

  <h1>Search Results</h1>

<ul>

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <h2>{{ message }}</h2>
      {% endfor %}
  </ul>
  {% endif %}


  {% if not messages %}
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">NameBooks</th>
      </tr>
    </thead>
    <tbody>
  {% for name in object_list %}
    <!-- <li>
      <h2><a href="{{book.book_author}}/{{book.book_name}}/">{{ book.book_name }}</a></h2>
    </li> -->
    
      
        <tr>
          <td>{{forloop.counter}}</td>
          <td><h2>{{ name.name }}</a></h2></td>
        </tr>
     

  {% endfor %}
</tbody>
</table>

{% endif %}


</ul>
</body>

Django_app/main/templates/main/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
   

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/sign.css' %}" type="text/css" />

    <title>Sign_Up</title>
</head>
{% block content %}

<div class="container mt-4">
    
    <div class="p-3 m-3">

        
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">

            <hr>
            </div>
            <h3 class="alert alert-success rounded-pill" style="text-align:center">Create an Account</h3>
            <form action="/signup" method="POST">
                
                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
                <!-- firstname -->
                <div class="form-group">
                    <label for="">First Name</label>
                    <input type="text" name="firstname"
                     id="" value="{{values.first_name}}" class="form-control form-control-sm" 
                     placeholder="">
                </div>

                <!-- last name -->
                <div class="form-group">
                    <label for="">Last Name</label>
                    <input type="text" name="lastname" 
                    id="" value="{{values.last_name}}" class="form-control form-control-sm"
                    >
                </div>

                <!-- phone -->
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" 
                    id="" class="form-control form-control-sm"
                    value="{{values.phone}}"
                    placeholder="9876543210"
                    >
                </div>
                <!-- email -->
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id=""
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>


                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id=""
                     class="form-control form-control-sm">
                </div>

                <!--Checkme button-->
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                <button type="submit" class="btn btn-sm btn-success col-lg-12">Create an account</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}